[package]
name = "dynamic_image_classification"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "~0.17", features = ["train", "wgpu", "vision", "tui", "metrics"] }
image = "*"
rand = "*"
burn-train = "*"
log = "*"
log4rs = "*"
